### ISSUE TITLE
Hide back button on product page when navigating to it from an external link

### ISSUE THREAD

**Issue by ATMarcks** [ATMarcks/csup-ordering-form#2]
The back button on the product page acts the same as the back button in your browser. This means that if you navigate to a product page via an external URL, such as being linked to `/products/1`, the `Back` button will navigate you away from the website. In the event that the user navigates to a product page from an external link the back button should be hidden.

**Comment by lalov1** [comment]
This would great with this functionality.

**Comment by ATMarcks** [comment]
Should be resolved by https://github.com/ATMarcks/csup-ordering-form/commit/06eca9710f9d1a718ae91b4d55448f0f6c2387df
