### ISSUE TITLE
Clean up cart buttons on cart page when using mobile

### ISSUE THREAD

**Issue by ATMarcks** [ATMarcks/csup-ordering-form#3]
The buttons on the cart page currently look a bit cramped when on mobile so some margins should be added:

![screenshot from 2018-07-09 00-33-07](https://user-images.githubusercontent.com/11085692/42434276-cf53be7e-830f-11e8-91c6-aa2deb807a2e.png)

**Comment by lalov1** [comment]
Yes, that would be nice or to add them in a bootstrap row

**Comment by ATMarcks** [comment]
Resolved in https://github.com/ATMarcks/csup-ordering-form/commit/83b0b615e209a7f332840380765229df60d9ffd1
