### ISSUE TITLE
Allow users to delete their information

### ISSUE THREAD

**Issue by ATMarcks** [ATMarcks/csup-ordering-form#4]
On the cart page users can edit their information but not delete their information. Although their information is deleted once their session is over, it would probably still be a good feature to add.

![screenshot from 2018-07-09 00-39-21](https://user-images.githubusercontent.com/11085692/42434510-a4e1e0ca-8310-11e8-8d2e-c89490d594cc.png)

**Comment by lalov1** [comment]
They are able to edit the information, so this should suffice for right now.

**Comment by ATMarcks** [comment]
We may(?) have discussed this at the last meeting but I think that it's a possibly that someone will make an order and only use the `Download Cart` button without submitting a request. After doing so they may want to make sure that their information is deleted from the website the next time a user visits it.

The methods required to clear out your order information are already there, so it wasn't difficult to implement. I can remove the button if you'd like, however.

How it looks:
![screenshot from 2018-07-14 19-45-21](https://user-images.githubusercontent.com/11085692/42729745-54c574ba-879f-11e8-9482-379d60b4d595.png)

After pressing the button the following alert appears:
![screenshot from 2018-07-14 19-49-44](https://user-images.githubusercontent.com/11085692/42729746-57874b42-879f-11e8-859e-8ca9cd676021.png)

added in https://github.com/ATMarcks/csup-ordering-form/commit/615b73a8f13178aacf4531849251646a1aaef8b2
