### ISSUE TITLE
Add handling for invalid items in the cart

### ISSUE THREAD

**Issue by ATMarcks** [ATMarcks/csup-ordering-form#5]
The following scenario is likely to happen:

- Product ID 3 is added to the catalog
- A user adds this product to their cart
- The catalog is updated and product ID 3 is removed
- The user visits the website and they now have a product in their cart that no longer exists
- Something will probably break

I think the best solution is to remove nonexistent products from a users cart. Perhaps notify them that this has happened as well?

**Comment by lalov1** [comment]
I don't think we need to notify them, but we should remove it from their cart.

**Comment by ATMarcks** [comment]
Resolved via https://github.com/ATMarcks/csup-ordering-form/commit/7bdfd870c05ce9e0d95a49ff2c274b9fcf718bb3
