### ISSUE TITLE
Make catalog somewhat hot-swappable in prod

### ISSUE THREAD

**Issue by ATMarcks** [ATMarcks/csup-ordering-form#6]
The way the program builds right now the catalog is minified inside of `app.js` and every time a change is made to the catalog the app will have to be rebuilt.

The catalog should instead be served as-is (move to the `static` dir?) or maybe served from the backend (if we end up using one)

**Comment by lalov1** [comment]
Yes, I think this is a good enhancement!

**Comment by ATMarcks** [comment]
https://github.com/ATMarcks/csup-ordering-form/commit/b4d4adc4e5ab1fa5f90c4880db6fdb4e5ad5a48f refactors the catalog into a global context. Since making the catalog hot swappable will involve having to periodically fetch the catalog (probably on every `getCart()`, this will reduce the number the number of requests required

Additionally https://github.com/ATMarcks/csup-ordering-form/commit/e395c2f5dfa58992fdead6a0e62e32d4e2219fbe allows for the backend to work while in development mode, so if we decide to serve it from a backend the app will still be functional without having to build for prod

**Comment by ATMarcks** [comment]
Resolved via https://github.com/ATMarcks/csup-ordering-form/commit/7bdfd870c05ce9e0d95a49ff2c274b9fcf718bb3
