### ISSUE TITLE
Edit Information button on confirmation page

### ISSUE THREAD

**Issue by lalov1** [ATMarcks/csup-ordering-form#7]
We shouldn't need the **Edit Information** button on the confirmation page. Also, we should have another message like this:
https://secure.csupueblo.edu/cae/craf-thank-you.asp

Maybe include some text that they are going to receive a copy soon.

**Comment by ATMarcks** [comment]
should be resolved by https://github.com/ATMarcks/csup-ordering-form/commit/d9a522bee45cc91590fa165a45eae6890f5d7a90

The following confirmation appears when you submit an order request:

![screenshot from 2018-07-12 21-30-01](https://user-images.githubusercontent.com/11085692/42729550-ae0485ae-8798-11e8-8d22-ad4efc83cb4a.png)

The "Continue with another order" button both takes the user to the home page but retains the account information they put in earlier. If they navigate away from the page without clicking that button the account information in localstorage is deleted. Feel free to reopen with additional changes are needed
